services:
  - type: web
    name: chamilo-on-render
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_NAME
        value: chamilo-demo-01.onrender.com
      - key: CHAMILO_DATA
        value: /var/www/chamilo-data
      - key: DATABASE_HOST
        value: <host_db>
      - key: DATABASE_USER
        value: <user_db>
      - key: DATABASE_PASSWORD
        value: <password_db>
      - key: DATABASE_NAME
        value: <bdname>
    disk:
      name: chamilo-data
      mountPath: /var/www/chamilo-data
      sizeGB: 2
